language: rust

rust: nightly

os: linux

dist: bionic

env:
  matrix:
    - ARCH="riscv64"
    - ARCH="riscv32"
    - ARCH="x86_64"
    - ARCH="aarch64"
    - ARCH="mipsel"

before_script:
  - rustup component add rustfmt-preview
  - make env

script:
  - cargo fmt -- --check
  - make build
  - make doc
