[package]
name = "trapframe"
version = "0.1.0"
authors = ["Runji Wang <wangrunji0408@163.com>"]
edition = "2018"
description = "Abstraction of CPU for OS development on multiple architectures."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.8"
raw-cpuid = "7.0.3"

[target.'cfg(any(target_arch = "riscv32", target_arch = "riscv64"))'.dependencies]
riscv = "0.5"

[patch.crates-io]
uefi = { git = 'https://github.com/rcore-os/uefi-rs', branch = "alloc-align" }

[workspace]
members = [
    "examples/uefi",
]
