[package]
name = "trapframe"
version = "0.1.6"
authors = ["Runji Wang <wangrunji0408@163.com>"]
edition = "2018"
description = "Handle Trap Frame across kernel and user space on multiple ISAs."
homepage = "https://github.com/rcore-os/trapframe-rs"
documentation = "https://docs.rs/trapframe"
readme = "README.md"
keywords = ["no_std", "interrupt", "bare-metal", "x86_64", "riscv"]
categories = ["no-std", "embedded"]
license = "MIT"
repository = "https://github.com/rcore-os/trapframe-rs"
exclude = ["docs", ".idea"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.9"
raw-cpuid = "7.0.3"

[target.'cfg(any(target_arch = "riscv32", target_arch = "riscv64"))'.dependencies]
riscv = "0.5"
